### ISSUE TITLE
Add padding

### ISSUE THREAD

**Issue by adamzr** [GideonLeGrange/haveibeenpwned#4]
Have I Been Pwned added a new privacy feature: padding. See https://haveibeenpwned.com/API/v3#PwnedPasswordsPadding Can we add it here?

**Comment by GideonLeGrange** [comment]
Thanks for reporting this. 

Padding is added in release 2.0. It's a major release, since when adding your request from #3, it became unfeasible to use overloaded constructors, and I decided to make a builder to configure the API. 

I've pushed 2.0 to Maven Central and it should show up there overnight. 

Please test and let me know how it works for you (I tested the changed call with and without padding, and it works).
